### ISSUE TITLE
Add-ons que falham no KodiAppleTv4

### ISSUE THREAD

**Issue by pedrofscaetano** [joaomvfsantos/joaomvfsantos.github.io#1]
Olá João, depois de resolvido a questão do Ok Goals, deixo aqui uma lista de todos os add-ons que não consigo abrir. Era interessante, tal como se fez com o fightnight, expor os problemas para fazer os respectivos uptdates. Abraço.

Não compativeis c/ Apple TV Kodi
-Music Box
-Mr Piracy
-Addon Installer
-Hevc Blurray
-123 Movies
-Velocity

**Comment by joaomvfsantos** [comment]
Olá, não utilizo nenhum desses plugins e infelizmente não tenho tempo para ir individualmente verificar qual o problema de cada um deles para reportar o bug. Vou fechar este issue.

**Comment by joaomvfsantos** [comment]
Já agora, podes sempre usar esta versão do Kodi para o tvOS http://mirrors.kodi.tv/nightlies/darwin/tvos/kodi-20151230-f8daf8c-yab-tvos.deb Usa a versão 16 do Kodi e deve ter menos problemas.
